### ISSUE TITLE
Badge Build Debug Validation checks

### ISSUE THREAD

**Issue by rlucero** [dczia/Defcon31-Badge#36]
Hardware tests needed:

blinking LEDs, red, green, blue
All buttons are detected (10 key switches + 2 rotary encoder buttons)
Encoders working
OLED screen working
Audio working
SD card working
I don't really have a good way to verify sync in/out and midi in/out in a quick way, so I'm going to ignore those

Ideally the badge boots up, two lines on the screen, top line is a link to the github, bottom is status.  LEDS cycle solid colors, red/green/blue.  Pressing a button is obvious either on the screen or highlighting with LED.  Pressing encoder shows on screen.  Rotating encoder shows on screen and/or plays another sample to test the audio path.  Boot up shows whether a SD card was detected but assume the SD card is blank.

I just want to drop this on the badge as they come out of the oven to A/B test them as rework needed or ready to ship
@skafreak / @catblade / @Ancient123 is there a way we can stitch a debug check?

**Comment by catblade** [comment]
Will look at it this weekend.  We have 2 encoder knobs.  What's the plan for the code there?  We'll want it easy for one of us to change it so we can test both?

**Comment by skafreak** [comment]
I believe this was provided, but reopen if we need improvements
