### ISSUE TITLE
Boot fails if no samples on SD Card / SD Missing / Other SD Error

### ISSUE THREAD

**Issue by lithochasm** [dczia/Defcon31-Badge#59]
My production v1 badge fails to run. First I did not have any samples on the SD card, but after putting them in the samples directory, there is still no output. Maybe my SD is bad? Files written to card from my mac, plays fine on other computers, but is not seen on the badge.

main.py output:
Traceback (most recent call last):
  File "main.py", line 61, in <module>
  File "SequencerState.py", line 154, in __init__
OSError: [Errno 2] No such file/directory

**Comment by skafreak** [comment]
This shouldn't have been happening. Are you using the code in the production folder? There should be error handling that spits out a message but then continues (tested on production v1.1 board).

**Comment by lithochasm** [comment]
Looks like it was actually looking for samples in the flash of the pi. The sample folder is not in the prod folder so if you dont copy that over, it throws an error.
